name: Test Node.js App

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: Install dependencies
      run: npm ci

    - name: Run tests frontend
      run: |
        cd frontend    # Cambia al directorio "frontend"
        npm install 
        npm test       # Ejecuta los tests

    - name: Run tests backend
      run: |
        cd backend    # Cambia al directorio "frontend"
        npm install 
        npm test       # Ejecuta los tests
